# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@/=./",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"
]

[invariant]
runs = 128
depth = 128
# fail_on_revert = false
# PRO of fail_on_revert = false --> quickly write open invariants tests and quickly write them with minimal handlers functions
# CONS --> Harder to make calls that actually make sense 
# So, good for very small contracts, but not great for complex contracts
#
fail_on_revert = true

